### ISSUE TITLE
Code for training and data set processing

### ISSUE THREAD

**Issue by Ethevliu** [sijang/SpachTransformer#2]
I have run your spach Transformer model for 3D reconstruction, but the model keeps reporting errors. I hope you can provide relevant code for training and data set processing.

**Comment by sijang** [comment]
I recently added a python code for training (train.py).
Please let me know if it is not working.
I checked it works.

**Comment by Ethevliu** [comment]
Thanks for the training code you provided, I took my data set (128*128*128) as the input of the model, and also tried to cut the data set to the size of 96*96*96 as the input, but I kept reporting errors:
![image](https://github.com/user-attachments/assets/c5d73213-6209-4a6d-9087-33e32fa1a414)
I have modified this error for many times, but it has not been effectively solved. I found that the input x changed from five dimensions to four dimensions in the previous step, which caused an error. Please check whether the model code is wrong.

**Comment by sijang** [comment]
I believe you are still using 128x128x128.
The problem is related to swin_window_size.

I updated the code (model/SpachTransformer.py) for the case of 128x128x128.
So you need to update your code too.

I updated the training example "train.py" also.
I checked it it works with:
`python train.py --simulated_img_size 128 --num_epochs 25 --batch_size 1 --learning_rate 0.0001`

**Comment by Ethevliu** [comment]
Thanks for your correction and help, I have successfully started running. Also want to ask you, if I input the image is 128*128*64, can the model run normally? Do you also need to adjust the size of the sliding window?

**Comment by sijang** [comment]
No problem. I suggest to change swin_window_size accordingly e.g., (8, 8, 6?).
